apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: k175/project-k:api
          name: api
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: env