apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
spec:
  ports:
  - port: 30800
    protocol: TCP
    targetPort: 30800
    nodePort: 30800
  selector:
    app: api
  type: NodePort