apiVersion: v1
kind: Service
metadata:
  labels:
    app: front
  name: front
spec:
  ports:
  - port: 30500
    protocol: TCP
    targetPort: 30500
    nodePort: 30500
  selector:
    app: front
  type: NodePort