apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeSelector:
        kubernetes.io/hostname: vm-38
      containers:
      - image: mysql/mysql-server
        name: mysql
        envFrom:
          - configMapRef:
              name: env
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: mysql-data-mount
      volumes:
        - name: mysql-data-mount
          hostPath:
            path: /home/user/mysql-data-mount
            type: DirectoryOrCreate