apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql/mysql-server
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: "project_k"
        - name: MYSQL_USER
          value: "project_k"
        - name: MYSQL_PASSWORD
          value: "project_k"
        - name: MYSQL_ROOT_PASSWORD
          value: "project_k"
      volumes:
        - name: mysql-data-mount
          persistentVolumeClaim:
            claimName: mysql-data
