services:
  front: 
    container_name: front
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    build: 
      context: front
      dockerfile: Dockerfile
    image: k175/project-k:front
    tty: true
    ports:
      - "30500:30500"
    volumes:
      - ./front:/app
      - /app/node_modules
    init: true
    environment:
      API_URL: ${API_URL}
    

  api:
    container_name: api
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./api/app:/app/src
    build:
      context: api
      dockerfile: Dockerfile
    image: k175/project-k:api
    ports:
      - "30800:30800"
    environment:
      ORIGINS: ${ORIGINS}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}


  mysql:
    image: mysql/mysql-server
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
